# Site settings
title: Always Learning
header-img: img/home-bg.png
email: mdkruszewski@gmail.com
copyright_name: mkruszewski89
description: > # this means to ignore newlines until "baseurl:"
  coming soon
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mkruszewski89
learn_profile: mkruszewski89
email_username: mdkruszewski@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
